Fix issues with quoting
austinhyde/ansible-sshjail pull request #36
Opened 2021-08-15 19:29 UTC by austinhyde

Fixes #34. There are some cases where quote stripping (needed when
ansible would otherwise try to run sudo in a jail) would remove too
little or too many quotes. This attempts to rectify this using
shlex-based parsing (mostly).

2021-08-16 12:43 UTC, grembo requested changes
Tested this change with a relatively complex playbook and I got this error message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'Requested entry (plugin_type: connection plugin: sshjail setting: retries ) was not defined in configuration.'
```

This wasn't caused by this change though, but by 7e1442948b1ca2289d970f17281fd54ba2275190.

When renaming "reconnection_retries" back to "retries" in sshjail.py, I can execute my playbooks successfully, so I think the parser change works just fine now.

Still requesting change, so maybe the retries issue could also be resolved in here (+ address my nitpicking about trailing whitespace).

2021-08-16 12:43 UTC, grembo commented on sshjail.py
> +
This line has trailing whitespaces

2021-08-16 16:06 UTC, grembo commented
> When renaming "reconnection_retries" back to "retries" in sshjail.py, I can execute my playbooks successfully, so I think the parser change works just fine now.
> 
> Still requesting change, so maybe the retries issue could also be resolved in here (+ address my nitpicking about trailing whitespace).

okay, so this change was due to https://github.com/ansible/ansible/commit/a2239d88191794f0f8f1d21c7a63ecd85ec4349e, which landed first in 2.11.3

I upgraded my local installation from 2.11.2 to 2.11.3 now and added an ansible minimum version requirement to my playbooks.

I also opened #37 to add a check to the module, so that there is a structured error message for others running into this.

2021-12-20 23:32 UTC, durin42 commented
FWIW I'm having to apply this patch for Ansible 2.12. It looks like the fix was only applied on the 2.11 branch?

2021-12-20 23:59 UTC, grembo commented
> FWIW I'm having to apply this patch for Ansible 2.12. It looks like the fix was only applied on the 2.11 branch?

There is some confusion - the patch to sshjail (#34 or #36) is required in all cases, but while testing #36 I noticed that sshjail didn't work at all on certain versions of ansible (2.11.0, 2.11.1, and 2.11.2) due to a bug in those versions.

2025-01-20 16:31 UTC, closed without merging